### ISSUE TITLE
object_path vulnerability fix breaks pathing of related libraries

### ISSUE THREAD

**Issue by devinci** [mariocasciaro/object-path#102]
After applying the audit fix for this package the following libraries pathing broke.
```
ERROR in ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: Cannot find module 'object-path'
Require stack:
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/utility/get-context-directory.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/project-relative.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/webpack-protocol.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/index.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/lib/process/index.js
- /home/circleci/project/node_modules/resolve-url-loader/index.js
- /home/circleci/project/node_modules/loader-runner/lib/loadLoader.js
- /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js
- /home/circleci/project/node_modules/webpack/lib/NormalModule.js
- /home/circleci/project/node_modules/webpack/lib/NormalModuleFactory.js
- /home/circleci/project/node_modules/webpack/lib/Compiler.js
- /home/circleci/project/node_modules/webpack/lib/webpack.js
- /home/circleci/project/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
- /home/circleci/project/node_modules/@angular-devkit/build-webpack/src/index.js
- /home/circleci/project/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/circleci/project/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/circleci/project/node_modules/@angular-devkit/architect/node/index.js
- /home/circleci/project/node_modules/@angular/cli/models/architect-command.js
- /home/circleci/project/node_modules/@angular/cli/commands/build-impl.js
- /home/circleci/project/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/circleci/project/node_modules/@angular-devkit/schematics/tools/index.js
- /home/circleci/project/node_modules/@angular/cli/utilities/json-schema.js
- /home/circleci/project/node_modules/@angular/cli/models/command-runner.js
- /home/circleci/project/node_modules/@angular/cli/lib/cli/index.js
- /home/circleci/project/node_modules/@angular/cli/lib/init.js
- /home/circleci/project/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/adjust-sourcemap-loader/codec/utility/get-context-directory.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/adjust-sourcemap-loader/codec/project-relative.js:6:27)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at /home/circleci/project/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:172:11
    at loadLoader (/home/circleci/project/node_modules/loader-runner/lib/loadLoader.js:32:11)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/home/circleci/project/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/home/circleci/project/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/circleci/project/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/circleci/project/node_modules/webpack/lib/NormalModule.js:446:15)

ERROR in ./src/styles/theme.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: Cannot find module 'object-path'
Require stack:
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/utility/get-context-directory.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/project-relative.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/webpack-protocol.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/index.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/lib/process/index.js
- /home/circleci/project/node_modules/resolve-url-loader/index.js
- /home/circleci/project/node_modules/loader-runner/lib/loadLoader.js
- /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js
- /home/circleci/project/node_modules/webpack/lib/NormalModule.js
- /home/circleci/project/node_modules/webpack/lib/NormalModuleFactory.js
- /home/circleci/project/node_modules/webpack/lib/Compiler.js
- /home/circleci/project/node_modules/webpack/lib/webpack.js
- /home/circleci/project/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
- /home/circleci/project/node_modules/@angular-devkit/build-webpack/src/index.js
- /home/circleci/project/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/circleci/project/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/circleci/project/node_modules/@angular-devkit/architect/node/index.js
- /home/circleci/project/node_modules/@angular/cli/models/architect-command.js
- /home/circleci/project/node_modules/@angular/cli/commands/build-impl.js
- /home/circleci/project/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/circleci/project/node_modules/@angular-devkit/schematics/tools/index.js
- /home/circleci/project/node_modules/@angular/cli/utilities/json-schema.js
- /home/circleci/project/node_modules/@angular/cli/models/command-runner.js
- /home/circleci/project/node_modules/@angular/cli/lib/cli/index.js
- /home/circleci/project/node_modules/@angular/cli/lib/init.js
- /home/circleci/project/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/adjust-sourcemap-loader/codec/utility/get-context-directory.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/adjust-sourcemap-loader/codec/project-relative.js:6:27)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at /home/circleci/project/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:172:11
    at loadLoader (/home/circleci/project/node_modules/loader-runner/lib/loadLoader.js:32:11)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/home/circleci/project/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/home/circleci/project/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/circleci/project/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/circleci/project/node_modules/webpack/lib/NormalModule.js:446:15)

ERROR in Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: Cannot find module 'object-path'
Require stack:
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/utility/get-context-directory.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/project-relative.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/webpack-protocol.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/codec/index.js
- /home/circleci/project/node_modules/adjust-sourcemap-loader/lib/process/index.js
- /home/circleci/project/node_modules/resolve-url-loader/index.js
- /home/circleci/project/node_modules/loader-runner/lib/loadLoader.js
- /home/circleci/project/node_modules/loader-runner/lib/LoaderRunner.js
- /home/circleci/project/node_modules/webpack/lib/NormalModule.js
- /home/circleci/project/node_modules/webpack/lib/NormalModuleFactory.js
- /home/circleci/project/node_modules/webpack/lib/Compiler.js
- /home/circleci/project/node_modules/webpack/lib/webpack.js
- /home/circleci/project/node_modules/@angular-devkit/build-webpack/src/webpack/index.js
- /home/circleci/project/node_modules/@angular-devkit/build-webpack/src/index.js
- /home/circleci/project/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/circleci/project/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/circleci/project/node_modules/@angular-devkit/architect/node/index.js
- /home/circleci/project/node_modules/@angular/cli/models/architect-command.js
- /home/circleci/project/node_modules/@angular/cli/commands/build-impl.js
- /home/circleci/project/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/circleci/project/node_modules/@angular-devkit/schematics/tools/index.js
- /home/circleci/project/node_modules/@angular/cli/utilities/json-schema.js
- /home/circleci/project/node_modules/@angular/cli/models/command-runner.js
- /home/circleci/project/node_modules/@angular/cli/lib/cli/index.js
- /home/circleci/project/node_modules/@angular/cli/lib/init.js
- /home/circleci/project/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/adjust-sourcemap-loader/codec/utility/get-context-directory.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/home/circleci/project/node_modules/adjust-sourcemap-loader/codec/project-relative.js:6:27)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
```

**Comment by lgodard** [comment]
@devinci 
Hi ! 
I encounter the same
did you solve your problem ? if yes, any hint ?

**Comment by devinci** [comment]
> @devinci
> Hi !
> I encounter the same error in my own module
> did you solve your problem ? if yes, any hint ?

I ended up not applying the audit fix and just using the package version required. Not ideal. But it solved the issue.
